# fly.toml file generated for budget-chat on 2022-10-12T18:50:23+05:30

app = "budget-chat"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 10000
  protocol = "tcp"

  [[services.ports]]
    port = 10000
